name: 🧾 Publish PDF

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on:
      - ubuntu-latest
    steps:
      - run: google-chrome --headless --disable-gpu --print-to-pdf=./resume.pdf --print-to-pdf-no-header https://mambax.github.io/mambax/
      - uses: actions/upload-artifact@v2
        with:
          name: resume
          path: resume.pdf