name: 🧾 Publish PDF

on:
  page_build:

jobs:
  generate:
    runs-on:
      - ubuntu-latest
    steps:
      - run: google-chrome --headless --disable-gpu --print-to-pdf=resume.pdf --print-to-pdf-no-header https://mambax.github.io/mambax/
      - uses: actions/upload-artifact@v2
        with:
          name: resume
          path: resume.pdf

  combine:
    needs: 
      - generate
    runs-on:
      - ubuntu-latest
    container:
      image: minidocks/ghostscript
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v2
        with:
          name: resume
          path: _resume
      - run: gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dAutoRotatePages=/None -sOutputFile=resume-with-cover.pdf pdf/cover.pdf _resume/resume.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: resume-with-cover
          path: resume-with-cover.pdf
  